FROM registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.13
COPY runtime/run_server_2pass.sh /workspace/FunASR/runtime/run_server_2pass.sh
WORKDIR /workspace/FunASR/runtime
EXPOSE 10095
CMD ["bash", "run_server_2pass.sh", "--certfile", "0"]
